version: '3.1'

services:
  app:
    image: diegogslomp/django-monitor
    build: .
    environment:
      SECRET_KEY: ')=^^v7e2e--*5swl77tij@w(t8z^v7j*^=s1na21#8e_&ymw%4'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - static:/usr/src/app/static
    networks:
      - frontend
      - backend
    ports:
      - '8000:8000'
    depends_on:
      - db

  monitord:
    image: diegogslomp/django-monitor
    build: .
    command: python manage.py monitord
    environment:
      SECRET_KEY: ')=^^v7e2e--*5swl77tij@w(t8z^v7j*^=s1na21#8e_&ymw%4'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db:
  static:
