version: "3.3"

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080    
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud-files:/mnt/data
    networks:
      - owncloud-network
      - traefik-public      
    deploy:
      placement:
        constraints:
          - node.labels.owncloud.owncloud-files == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.owncloud-http.rule=Host(`${OWNCLOUD_DOMAIN?Variable not set}`)
        - traefik.http.routers.owncloud-http.entrypoints=http
        - traefik.http.routers.owncloud-http.middlewares=https-redirect
        - traefik.http.routers.owncloud-https.rule=Host(`${OWNCLOUD_DOMAIN?Variable not set}`)
        - traefik.http.routers.owncloud-https.entrypoints=https
        - traefik.http.routers.owncloud-https.tls=true
        - traefik.http.routers.owncloud-https.tls.certresolver=le
        - traefik.http.services.owncloud.loadbalancer.server.port=8080

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud-mysql:/var/lib/mysql
    networks:
      - owncloud-network
    deploy:
      placement:
        constraints:
          - node.labels.owncloud.owncloud-mysql == true      

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - owncloud-redis:/data
    networks:
      - owncloud-network
    deploy:
      placement:
        constraints:
          - node.labels.owncloud.owncloud-redis == true      

volumes:
  owncloud-files:
  owncloud-mysql:
  owncloud-redis:

networks:
  owncloud-network:
  traefik-public:
    external: true