version: "3"

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8484:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - data:/var/lib/pgadmin

volumes:
  data:
