version: "3.1"

services:
  dc1:
    image: diegogslomp/samba-ad-dc
    hostname: DC1
    privileged: true
    environment:
      SMB_VERSION: latest
      REALM: SAMDOM.EXAMPLE.COM
      SEARCH_DOMAIN: samdom.example.com
      DOMAIN: SAMDOM
      ADMIN_PASS: Passw0rd
