global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: "dgs-monitor"

rule_files:
  - "/etc/prometheus/prometheus.rules.yml"

scrape_configs:

  - job_name: "python"

    scrape_interval: 1m

    static_configs:
      - targets: ["localhost:8083"]
