version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8083:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ${HOME}/repos
        target: /repos
    environment:
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"


volumes:
  jenkins_home:
