version: '3.3'

services:
  app:
    image: louislam/uptime-kuma:1
    volumes:
      - data:/app/data
    restart: unless-stopped
    ports:
      - target: 3001
        published: 3001
        mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  data: