version: "3.3"

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - target: 80
        published: 8484
        mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - target: 5432
        published: 5432
        mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  pgadmin:
  data:
